version: "3.8"


services:
  # TODO: add nginx:
  backend:
    build: ./backend/
    ports:
      - "${BE_INNER_UVICORN_PORT:-8080}:8080"
    volumes:
      - ./backend:/opt/project
    command: "uvicorn main:app --port ${BE_INNER_UVICORN_PORT:-8080} --host 0.0.0.0 --reload"
